name = "SPEDAS"
uuid = "3930f61c-4d81-4846-ab8f-357babe068a6"
version = "0.2.1"
authors = ["Zijin Zhang <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs"]

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
GeoCotrans = "4624b3bc-fe35-44f8-bfa8-722ff9c0e307"
HybridArrays = "1baab800-613f-4b0a-84e4-9cd3431bfbb9"
IRBEM = "d0b46c7b-8a8f-4d20-a1b4-6e9a4a1e4e5f"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MinimumVarianceAnalysis = "5a74c7d3-1edb-47ee-a7ac-bdb4b3eeab9d"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
PlasmaWaves = "12efb907-3f94-4823-94fe-a707db5a5005"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SignalAnalysis = "df1fea92-c066-49dd-8b36-eace3378ea47"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TimeseriesUtilities = "31d49243-0742-49c1-b8d2-db113b74581e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]

[compat]
DataInterpolations = "7, 8"
Dates = "1"
Dictionaries = "0.4"
DimensionalData = "0.29"
DimensionfulAngles = "0.2.1"
GeoCotrans = "0.0.1, 0.1"
HybridArrays = "0.4"
IRBEM = "0.1"
Intervals = "1.10.0"
LinearAlgebra = "1"
MinimumVarianceAnalysis = "0.1"
NaNStatistics = "0.6"
NamedTupleTools = "0.14.3"
PlasmaWaves = "0.1.1"
Reexport = "1"
SignalAnalysis = "0.10"
SpaceDataModel = "0.2"
StaticArrays = "1"
Statistics = "1"
TOML = "1"
TimeseriesUtilities = "0.1.1"
Unitful = "1"
julia = "1.10"
