name = "SPEDAS"
uuid = "3930f61c-4d81-4846-ab8f-357babe068a6"
version = "0.2.5"
authors = ["Zijin Zhang <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
GeoCotrans = "4624b3bc-fe35-44f8-bfa8-722ff9c0e307"
IRBEM = "d0b46c7b-8a8f-4d20-a1b4-6e9a4a1e4e5f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MinimumVarianceAnalysis = "5a74c7d3-1edb-47ee-a7ac-bdb4b3eeab9d"
MultiSpacecraftAnalysis = "162efcab-a561-4df9-ac40-20243229ff2c"
PlasmaWaves = "12efb907-3f94-4823-94fe-a707db5a5005"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SignalAnalysis = "df1fea92-c066-49dd-8b36-eace3378ea47"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TimeseriesUtilities = "31d49243-0742-49c1-b8d2-db113b74581e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataInterpolations = "7, 8"
Dates = "1"
DimensionalData = "0.29"
DimensionfulAngles = "0.2.1"
GeoCotrans = "0.0.1, 0.1, 0.2"
IRBEM = "0.1.7"
LinearAlgebra = "1"
MinimumVarianceAnalysis = "0.1"
MultiSpacecraftAnalysis = "0.1.1"
PlasmaWaves = "0.1.1"
Reexport = "1"
SignalAnalysis = "0.10"
SpaceDataModel = "0.2.3"
StaticArrays = "1"
TOML = "1"
TimeseriesUtilities = "0.1.5"
Unitful = "1"
julia = "1.10"
