[deps]
CDAWeb = "950ff2a9-823f-469c-91a7-754a5d85edca"
CDFDatasets = "075ae62b-f872-4368-b383-31e3aa6c3154"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
IRBEM = "d0b46c7b-8a8f-4d20-a1b4-6e9a4a1e4e5f"
MultiSpacecraftAnalysis = "162efcab-a561-4df9-ac40-20243229ff2c"
PlasmaWaves = "12efb907-3f94-4823-94fe-a707db5a5005"
PySPEDAS = "668d2cef-03a7-4c36-a521-7d1c6ddc8846"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
SPEDAS = "3930f61c-4d81-4846-ab8f-357babe068a6"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
SpacePhysicsMakie = "0c28ffd8-ae30-4a56-b2e4-f8332c621ad2"
Speasy = "09b745ad-c67d-442f-94a6-c7f4d1e4d861"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
CDAWeb = "0.1.4"
Documenter = "1.8"
PySPEDAS = "0.1.5"
SpaceDataModel = "0.2"
SpacePhysicsMakie = "0.2.3"
Speasy = "0.4.2"
